### PR TITLE
Use ${TEST_SRCDIR}/_main/ to reference test-data.

### PR DESCRIPTION
**Pull request by ensonic**
This has been recommened in:
https://bazel.build/concepts/dependencies#data-dependencies

and hopefully fixes the tests on buildkite, see
https://github.com/googlecloudrobotics/core/issues/417#issuecomment-2360650787

### CODE REVIEW

**Review by mering — APPROVED** [review]

**Comment by ensonic** [comment]
Meh, does not help:
https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/01920d9f-0c23-4acd-8ebd-c0d5540d82dc/src/app_charts/base/app_management_test/test.log

Now we get:
```
/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/753c46cd17f260bf584a727a9c58ca06/sandbox/linux-sandbox/2734/execroot/_main/bazel-out/k8-fastbuild/bin/src/app_charts/base/app_management_test.runfiles/_main/src/app_charts/base/app_management_test: line 34: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/753c46cd17f260bf584a727a9c58ca06/sandbox/linux-sandbox/2734/execroot/_main/bazel-out/k8-fastbuild/bin/src/app_charts/base/app_management_test.runfiles/_main/external/_main~non_module_deps~kubernetes_helm/helm: No such file or directory
```

**Comment by mering** [comment]
Maybe paths for external don't have a `_main` prefix?

**Comment by ensonic** [comment]
> Maybe paths for external don't have a `_main` prefix?
> 
> Can you test this locally somehow?
Yes on the githb ci and locally that test works. It is a normal unit-test (included by `bazel test //...`).

**Comment by mering** [comment]
Which Bazel version is Buildkite using? As runfiles are different among versions, this makes a big difference.

**Comment by ensonic** [comment]
> Which Bazel version is Buildkite using? As runfiles are different among versions, this makes a big difference.


https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4136#01920d9f-0c23-4acd-8ebd-c0d5540d82dc

suggests bazel at head ...

**Pull request merged**
