### PR TITLE
Log the error when we don't retry again.

### PR DESCRIPTION
**Pull request by ensonic**
This will more consistently log when a chart fails.

### CODE REVIEW

**Review by methylDragon — APPROVED** [review]
This will go a long way to ensuring we have some visibility into failures.

**Comment by methylDragon** [comment]
Might be a good idea to keep track of retry count and explicitly fail if it crosses a threshold though?

**Comment by vivekbagade** [comment]
> Might be a good idea to keep track of retry count and explicitly fail if it crosses a threshold though?

We should only count errors and fatalf in the case of client-go failures and not other failures. We don't want a single bad chartassignment bringing down the CAC

**Comment by ensonic** [comment]
I'll merge this then. If we keep logging an error due to infinite retries, it will be annoying, but at least visible.

**Pull request merged**
